examples/Elements/Sources/Elements.hx

Without the arrays being stored in variables it was just recreating the arrays every frame, throwing out the old one which could have been modified by the user.

Fixed Add & Delete buttons for list examples

---

Sources/zui/Zui.hx

They are public now so they can be used when you initialize zui with ```{ autoNotifyInput: false }```

expose onKeyDown, onKeyUp, onKeyPress

---

Sources/zui/Zui.hx

Seems to only pop up in vscode + kha extensions, but not KodeStudio.

comment out unused hover variable (silences vscode's problem page)

---

Sources/zui/Zui.hx

This change makes it possible to use arbitrary Id's (hashes and the like) instead of only array indices. This is useful when you display items that can be sorted (or change their order dynamically via logic code in your app) and keep their handle properties in sync (say a corresponding panel should stay open).
This might affect performance, but i haven't noticed anything worth mentioning in our app so far.

use Map<Int, Handle> instead of Array<Handle> for Handle.children

---

Sources/zui/Zui.hx

Here is a screenshot of 2 screenshots to showcase the problem :innocent: 
Notice how the red/orange background bleeds into the word `FLUSH 6 / 7` in the upper image. With this PR that won't happen anymore, as visible in the bottom image. This is especially noticeable if you have draggable windows.
We had a small conversation in kha irc about it as well:
```
4.7.2019 23:47 | dave: | i have some  alpha weirdness when i'm rendering a font to a rendertarget and then  that rendertarget to the screen. is it me being stupid, or is there  something broken in kha (happens in a normal debug html5 build as well,  not only in kodegarden)?  http://kodegarden.org/#be01da52bdab9fe8f62cb0a6b17436023837831b
4.7.2019 23:50 | Kyric: | probably would help if you didn't have high contrast checker patterns to …
```

use a custom shader for text rendering

---

Sources/zui/Zui.hx
changes.md

`isKeyDown` gets reset at the end of the draw function, so there was no way of knowing whether a key is pressed for a longer time than one frame.
This is needed for an upcoming PR on Armory2d :)

Add isKeyPressed variable

---

Sources/zui/Canvas.hx
Sources/zui/Ext.hx
Sources/zui/Popup.hx
Sources/zui/Themes.hx
Sources/zui/Zui.hx

This PR adds custom theme support for canvas.
**Changed:**
- Added UI Popup widget (very similar to Armorpaint)
- Added colorField UI component (like the color selection in Blender)
- Canvases now support custom themes
- Themes have names now
- Handles can be un-nested
Linked to https://github.com/armory3d/armory2d/pull/38 and https://github.com/armory3d/armory/pull/1513.

Custom theme support for canvas

---

Sources/zui/Canvas.hx
Sources/zui/Zui.hx

Canvas doesn't need to scale the elements height anymore because this is now handled during zooming in Armory2D.

Small scaling fixes

---

Sources/zui/Canvas.hx

This PR fixes anchors and their behaviour with parented elements and different scale settings :) The x and y coordinates of the elements are the offset from anchor position, so if the anchor is set to "Right", a negative x value is the margin of the element to the right border.
This should fix https://github.com/armory3d/armory/issues/1492

Fix anchors

---

Sources/zui/Zui.hx

Used `max()` to keep compatibility with outliner in Armory2D (e.g.)
Forgot this commit when opening https://github.com/armory3d/armory2d/pull/48. Now it should look like on the screenshots

Fix text element height for larger font sizes

---

Sources/zui/Zui.hx

see #105 
This PR implements a limit for the shown list when a combo is open. It's optional and defaults to -1 (show all elements) to keep the old behavior intact.
When it's active, the shown rows are limited to whatever was passed.
When the combo is opened, visible rows will automatically be offset so the previously selected element is at the top. And additionally, it's possible to scroll the list via mouse wheel now when the limit is active. I haven't had time to implement a proper scrollbar though.
Example combo with rows limited to `5`

limit visible combo elements and implement mouse wheel scrolling

---

Sources/zui/Ext.hx
Sources/zui/Themes.hx
Sources/zui/Zui.hx

- Fixed `Ext.colorField()` y position
- Prettier indentation (old behaviour still possible)
(Left: old, right: new)
- Implement panel background color (see `Basic` panel in the screenshot above)
- Denser alignment of panels (like Blender's `align` parameter for layouts)

Small improvements and adjustments

---

Sources/zui/Zui.hx

Right now we crash with an empty texts array with the combo. This fixes this.

Handle when texts array has an empty array

---

Sources/zui/Ext.hx

This change makes it so a text area correctly formats strings containing tab indentations. I made the modification in the textArea function so that it only affects the text area. Is this the right place to make the change?

Update text area to format tabs correctly

---

Sources/zui/Nodes.hx

Not a breaking change.
By default it is `Line`, you can use `CubicBezier` in `TNodeLink`.

add link_style & CubicBezier style

---

Sources/zui/Canvas.hx

Current behavior makes very difficult to correctly scale the UI
if you are also using something to automatically adjust it's dimensions
to match current window — such as Armory does.
More explanations and examples here → https://github.com/armory3d/armory/issues/1666

Removed canvas scaling in `Canvas.getAnchorOffset`.

---

Sources/zui/Zui.hx

Right now collisions are limited to the height of the element; Zui never considers the width of an image when detecting clicks. This addresses the issue. 
Since the way Zui handles input is related to the window width and the element heigth, it may be interesting in the future to have a better way to limit the collisions of elements on the x axis i.e. by having an endElementX().
If this is something that would be desired I may look into it. 
One of the situations where the collisions are faulty is for example when we have tooltips for tabs. the tooltip will appear for the whole window instead of just on hover of the Tab.

Make ui.image collisions limited to image width

---

Sources/zui/Popup.hx

Right now if the popup needed to scroll down to say go to a apply or cancel button, next time we would open a popup the window would be scrolled to as far as was set beforehand. This addresses the issue by reseting the scroll offset when closing the Popup.

Reset window scroll when closing the popup

---

Sources/zui/Nodes.hx

I think it is a nice enhancement for nodes to have a cutomizeable width. This is useful for nodes with longer STRING input fields or nodes with sliders which have a big range.
Concrete examples: I built a math expression node plugin for ArmorPaint 
I also built a comment node and I'm sure there are many others to benefit from it. Also in Blender not all nodes are of the same width.
_Attention_ If you accept this pull request, please correct nodes.NODE_W(node); in line 78 in UINodes.hx - ArmorPaint. I think it is not worth to hand in a pull request for it.

Add optional width attribute to nodes

---

Sources/zui/Zui.hx

Currently text input controls allow for cut and paste if they are readonly. This behavior can be observed in ArmorPaint's About... dialog box. See https://github.com/armory3d/armorpaint/issues/949

Disable cut and paste for readonly text input controls

---

Sources/zui/Zui.hx

Fixes https://github.com/armory3d/armorpaint/issues/1073
Description:
The German keyboard layout uses AltGr as a modifier key like Shift. For example AltGr + q = @ or AltGr + e = €.
The AltGr event is represented by Ctrl + Alt. Because of 
`if (!selecting && !isCtrlDown ) highlightAnchor = cursorX;`
in line 860 text input controls do not shift the hightlight anchor if AltGr is pressed. This yields a selection of the last character if AltGr + some other key is pressed. 
This PR extends this condition by (!isCtrlDown || (isCtrlDown && isAltDown)) to disallow ctrl pressed while allowing ctrl+alt pressed.

Do not select last character if AltGr was pressed

---

Sources/zui/Ext.hx

This PR makes hex codes much more usable in ArmorPaint.
Currently ArmorPaint enforces a 8-digit representation for hex colors, where the first two digits are the alpha value. Most hex codes out there are not in this format but have a "CSS-style". The PR introduces the following formats and conversions
1. ff83ff (rrggbb) --> ffff83ff
2. abc (rgb with the meaning rrggbb) --> ffaabbcc
3. c123 (argb with the meaning aarrggbb) --> cc112233
4. An optional # at the front, i.e. #00ff00 --> ff00ff00

Improve hex code parsing

---

Sources/zui/Nodes.hx

Imho it is better to be consistent between the RGB node and the Material Output node in ArmorPaint. Therefore I enabled the color wheel preview for the rgbapopup
Fixes parts of https://github.com/armory3d/armorpaint/issues/1106

Add colorwheel preview to rgbapopup

---

Sources/zui/Ext.hx

Colorwheels have the property that they close on mouse click if they are placed in an `UIMenu`. Imho this behavior is unfortunate because it does not allow for corrections in the picked color without having to reopen the color wheel.
It partially improves https://github.com/armory3d/armorpaint/issues/1277.
It implements parts of https://github.com/armory3d/armorpaint/issues/1106.
What I dislike about my change is the fact that it breaks the colorWheel API because it adds another parameter.

Prevent closing color wheel on mouse release

---

Sources/zui/Ext.hx
Sources/zui/Zui.hx

@[paolohuesp](https://github.com/paolohuesp) proposed in https://github.com/armory3d/armorpaint/issues/1106#issuecomment-907729666 to implement a value slider to lighten/darken colors just like it is done in Blender. This PR implements this request.
How is it implemented?
1. I added a new image called black_white_gradient.png. I could have painted the gradient using a four vertex rectangle and two vertex colors but Graphics2 does not support that and the API is not designed to have an additional second color. None the less it would be easy implement it that way. I couldn't add the slider to the existing image because the tint should not change the slider's greyscale. Thus adding an image texture seemed to be a suitable alternative. I could easily add a border, too, which was nice. The …

Add value slider for color picker

---

Sources/zui/Nodes.hx

ArmorPaint behaves a bit differently from Blender for duplicating nodes. In contrast to Blender ArmorPaint does not allow to move the node around after duplicating. Imho Blender's behavior is better. Therefore I changed it that the nodes can be moved.
How did I do it and how does it affect ArmorPaint's behavior?
- I use the upper left corner of last element in `pasteCanvas.nodes` as pivot point that is directly below the mouse cursor. Why? Suppose the user selects nodes one by one then it is the last one and probably the one where the context menu is opened. This was the most intuitive way imho. A slight improvement might be to always use the one where the context menu was opened but in case ctrl+c is used this does not work anyway. I use the left upper corner because this avoids clicking …

Paste nodes at mouse position and make them dragable

---

Sources/zui/Zui.hx

Implemented a search bar for combo boxes
How does it look like?
Does the appearance fit your taste? For example we could change the background if you wish.
What's the purpose?
I'd like to add the search bar at many many places.
- Image node will become way more convenient if able to type the file name. 
- For Blending modes 
- For selecting an object or to set a filter
- Maybe to replace the current node search?
- Basically it is useful in almost every combobox and is compatible with locales.
- It is the first step for a proper image/material/... selector for image node and other cases.
QUESTION: Currently it is `combo`'s the last parameter. Imho it is a very useful feature and it might be a good idea to set it as the third parameter if it will be used for most comboboxes. Didn't do it to …

Search bar for combo boxes

---

Sources/zui/Zui.hx

Implemented an option to live update the text input. This avoids the hack to use the internal textSelected and makes the option available to other places as well.
- The node search can be simplified by this
- It is easy to implement a live search for the browser now
- Maybe `Zui.textSelected` can be made private.
Please check carefully whether I broke something. In case the user decides to use live input the previous state can not be restored by Esc anymore but I think this is no real problem.

Live text input

---

Sources/zui/Ext.hx

It's way more beautiful and consistent with all other editors like this:
Limitation: only for mono space fonts.

Right align line numbers
