Sources/zui/Zui.hx

they were blank before but now they can be seen

Checkboxes displayed in windows native target

---

Sources/zui/Zui.hx

before it behaved weirdly. now it's super responsive and you can drag it really fast!

Scrollbar drag fixed

---

Sources/zui/Zui.hx

Also scrollbar handle ignored window offset, now works.

Window textures are resized if size changes.

---

Sources/zui/Ext.hx
Sources/zui/Zui.hx
examples/Calc/Sources/Elements.hx

It's mostly a preference than anything else.
It should be compatible with raw ints or Zui.LAYOUT_* and Zui.ALIGN_*

Abstract enums

---

Sources/zui/Zui.hx

for issue https://github.com/luboslenco/zui/issues/20

make the internal state of sliders public so that they can be sync'ed #20

---

Sources/zui/Ext.hx

- Ext.list initializes the handle.text property with the return value from getNameCB
- first entry in the list didn't display properly
- in case of an editable entry, it's also possible to display a custom label now

fix Ext.list

---

Sources/zui/Ext.hx

I wanted to add another option (to overwrite the label for the 'Add' button), then i noticed that 1 gazillion parameters a kinda insane to remember so moved them all to ListOpts. Think it's a good idea?
I'll also implement it for panelList() if you think it's worthwhile to have.
(The add label overwrite is also already included with the ListOpts.addLabel field).

use a struct to init list()

---

Sources/zui/Zui.hx
examples/Elements/Sources/Elements.hx

Let me know if you have feedback :)

add floatInput

---

Sources/zui/Zui.hx

This will highlight the whole string in a text or float input when it gains focus so the user can quickly overwrite that data with their new input.

Basic highlight support

---

Sources/zui/Zui.hx

The sliders handle.changed property was being overwritten.

set handle.changed correctly

---

Sources/zui/Canvas.hx

fix circular progress bar color

---

Sources/zui/Zui.hx

update window width calculation for vertical tabs

---

Sources/zui/Canvas.hx

Added an event when a text in a textInput element is submitted.

Add event for textInput

---

Sources/zui/Zui.hx

Added Hovered to Zui.State and made it so when we hover over an image it returns State.Hovered.

Hover over Images State

---

Sources/zui/Canvas.hx

When this gets merged we will start work on including textArea to armory2d

Support TextArea in Canvas

---

Sources/zui/Canvas.hx
examples/Canvas/Sources/Elements.hx

Reuse events array instead of creating new

---

Sources/zui/Zui.hx

Currently the slider's position is changed by clicking on the sliders number to change it directly. This behavior is unfortunate.
This PR fixes
https://github.com/armory3d/armorpaint/issues/1244
https://github.com/armory3d/armorpaint/issues/1222#issue-1087172113 item number 9.
https://github.com/armory3d/armorpaint/issues/1069 the slider issue mentioned here

Mimic Blender slider behavior

---

Sources/zui/Nodes.hx

Adds the technical foundation for https://github.com/armory3d/armorpaint/issues/927
Will add some explanatory texts to ArmorPaint nodes in the future. Though, it is hard for me to discover which nodes are hard to understand for users.

Add optional tooltips to nodes

---

Sources/zui/Ext.hx
Sources/zui/Nodes.hx

See https://github.com/armory3d/armorpaint/pull/1329

Color picker support for color wheel

---

Sources/zui/Ext.hx

The button did not scale appropriately

Fix picker button scaling issue

---

Sources/zui/Zui.hx

Useful fo further shortcut improvements in the main menu.

Add labels to radio and check
